#!/usr/bin/env bash
#Install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo cp sites-available/default sites-enabled/
sudo /etc/init.d/nginx start
