#!/usr/bin/env bash
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM; x=0;while [ $x -le 1 ]; do echo "To infinity and beyond"; sleep 2; done