#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration,
# displays Best School and then Hi on a new line
x=1
while [ $x -le 10 ]
do
    if [ $x == 10 ]
    then
        echo "hi"
    fi
    echo "Best School"
    ((x++))
done
