#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
x=1
while [ $x -le 10 ]
do
    if [ $x == 4 ]
    then
        echo "bad luck"
    elif [ $x == 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((x++))
done