#!/usr/bin/env bash
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
x=1
while [ $x -le 20 ]
do
    if [ $x == 4 ]
    then
        echo "bad luck from China"
    elif [ $x == 9 ]
    then
        echo "bad luck from Japan"
    elif [ $x == 17 ]
    then
        echo "bad luck from Italy"
    else
        echo $x
    fi
    ((x++))
done