#!/usr/bin/env bash
#
x="school"
if [ -e $x ];
then
    echo "school file exists" 
    if [ -s $x ];
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f $x ];
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi