#!/usr/bin/env bash
#if the file exists: school file exists
#if the file does not exist: school file does not exist
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)
x="school"
if [ -e $x ];
then
    echo "school file exists" 
    if [ -s $x ];
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f $x ];
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi