#!/usr/bin/env bash
#nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080
pkill apache
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
