#!/usr/bin/env bash
#Your Bash script must be 7 lines long or less
#There must be a new line at the end of the file
#You respect Bash script requirements
#You cannot use ;
#You cannot use &&
#You cannot use wget
#You cannot execute your previous answer file (Do not include the name of the previous script in this one)

pkill apache
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
